project_id = "omzwtfnqffseemrlylwu"

[functions.admin-manage-user-access]
verify_jwt = true

[functions.admin-manage-stripe-subscription]
verify_jwt = true

[functions.admin-bootstrap]
verify_jwt = false

[functions.auth-me]
verify_jwt = true
