-- SUPERSEDED — see docs/migrations/20260625120000_secure_quiz_and_module_ratings.sql
--
-- This earlier draft used REVOKE SELECT(is_correct) only, which does NOT
-- remove a pre-existing table-level SELECT grant. External audit flagged it
-- as insufficient: authenticated/anon could still read quiz_options.is_correct
-- via PostgREST. The replacement migration revokes table-level SELECT entirely,
-- routes member reads through the get-member-quiz edge function (service-role),
-- adds the transactional grading RPC, and access-gates module_ratings writes.
--
-- Do not apply this file. Use the 20260625120000 version instead.
