// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's basic identity in this Alchemy Academy app (email, user id, admin flag).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const userId = ctx.getUserId();
    const { data: roleRow } = await supabase.from("user_roles").select("role").eq("user_id", userId).eq("role", "admin").maybeSingle();
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail() ?? null,
      is_admin: Boolean(roleRow)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-courses.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.0";
import { z } from "npm:zod@^4.1.12";
var list_courses_default = defineTool2({
  name: "list_courses",
  title: "List courses",
  description: "List courses available in Alchemy Academy that the signed-in user can see, respecting the same row-level rules as the app (RLS runs as this user).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max number of courses to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("courses").select("id, title, subtitle, short_description, status").order("id", { ascending: true }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { courses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-certificates.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.110.0";
var list_my_certificates_default = defineTool3({
  name: "list_my_certificates",
  title: "List my certificates",
  description: "List certificates issued to the signed-in user in Alchemy Academy, including the course title, certificate number, issue date, and the public share link when the certificate is public.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    }
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("certificates").select("id, certificate_number, issued_at, revoked_at, public_slug, course_id, courses(title)").order("issued_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const siteUrl = process.env.SITE_URL ?? process.env.PUBLIC_SITE_URL ?? "";
    const rows = (data ?? []).map((r) => {
      const course = r.courses;
      return {
        id: r.id,
        certificate_number: r.certificate_number,
        issued_at: r.issued_at,
        revoked: Boolean(r.revoked_at),
        course_id: r.course_id,
        course_title: course?.title ?? null,
        public_link: r.public_slug && siteUrl ? `${siteUrl.replace(/\/$/, "")}/c/${r.public_slug}` : r.public_slug ? `/c/${r.public_slug}` : null
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(rows) }],
      structuredContent: { certificates: rows }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "omzwtfnqffseemrlylwu";
var mcp_default = defineMcp({
  name: "alchemy-academy-mcp",
  title: "Alchemy Academy",
  version: "0.1.0",
  instructions: "Tools for Alchemy Academy, an online interior-design school by Casa Alchemy Studio. Callers act as the signed-in student. Use `whoami` to confirm identity, `list_courses` to browse the catalog, and `list_my_certificates` to fetch issued certificates and their public share links.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_courses_default, list_my_certificates_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
