// Pilot quiz bank — 10 modules × 5 questions × 4 options.
// Source: docs upload "Alchemy Academy — 50 Quiz Questions (Para Aprovação)".
// Each entry maps to one course (by slug) and produces one quiz with 5 questions.
// Idempotency key: (course.id, quiz.title) — re-running the seeder replaces the
// matched quiz so admins can iterate copy without orphaning rows.

export type SeedOption = { text: string; correct: boolean };
export type SeedQuestion = { question: string; options: SeedOption[]; explanation: string };
export type SeedQuiz = {
  course_slug: string;
  course_title_hint: string;
  quiz_title: string;
  description: string;
  passing_score: number;
  max_attempts: number | null;
  questions: SeedQuestion[];
};

const q = (
  question: string,
  options: string[],
  correctIndex: number,
  explanation: string,
): SeedQuestion => ({
  question,
  explanation,
  options: options.map((text, i) => ({ text, correct: i === correctIndex })),
});

export const PILOT_QUIZZES: SeedQuiz[] = [
  {
    course_slug: "the-path-to-a-colourful-life",
    course_title_hint: "The path to a COLOURFUL life",
    quiz_title: "Module 1 · The Basics to Start — Knowledge Check",
    description: "Foundations of colour theory: colour wheel, warm vs cool, tint/shade/tone.",
    passing_score: 70,
    max_attempts: 3,
    questions: [
      q("What are the three primary colours on the traditional colour wheel?",
        ["Red, Green, Blue", "Red, Yellow, Blue", "Orange, Green, Purple", "Cyan, Magenta, Yellow"], 1,
        "The traditional (RYB) colour wheel used in art and interior design is based on Red, Yellow, and Blue as primary colours. These cannot be created by mixing other colours."),
      q("Which of the following is considered a 'warm' colour?",
        ["Blue", "Green", "Orange", "Purple"], 2,
        "Warm colours include red, orange, and yellow. They evoke feelings of warmth, energy, and cosiness — making them ideal for social spaces."),
      q("What is a 'tint' in colour theory?",
        ["A colour mixed with black", "A colour mixed with white", "A colour mixed with grey", "A colour at full saturation"], 1,
        "A tint is created by adding white to a pure colour, making it lighter. For example, pink is a tint of red. Tints create soft, airy atmospheres in interiors."),
      q("What is the difference between a 'shade' and a 'tone'?",
        ["Shade adds white; tone adds black", "Shade adds black; tone adds grey", "Shade adds grey; tone adds white", "They are the same thing"], 1,
        "A shade is created by adding black to a colour (making it darker), while a tone is created by adding grey (making it more muted and sophisticated). Tones are widely used in interior design for their subtlety."),
      q("Which colour relationship creates the strongest visual contrast?",
        ["Analogous colours", "Monochromatic colours", "Complementary colours", "Neutral colours"], 2,
        "Complementary colours sit directly opposite each other on the colour wheel (e.g., blue and orange). They create maximum contrast and visual energy when placed together."),
    ],
  },
  {
    course_slug: "the-sacred-bedroom",
    course_title_hint: "The sacred BEDROOM",
    quiz_title: "Module 2 · Bedroom — Knowledge Check",
    description: "Peaceful retreats: warm colours, cozy spaces, balancing warm palettes.",
    passing_score: 70,
    max_attempts: 3,
    questions: [
      q("Which warm colour palette is most recommended for creating a restful bedroom atmosphere?",
        ["Bright red and vivid orange", "Soft terracotta and muted blush", "Neon yellow and hot pink", "Pure white and stark black"], 1,
        "Soft, muted warm tones like terracotta and blush create a cocooning effect without overstimulating the senses. Bright, saturated warm colours can feel too energising for sleep."),
      q("What is the best way to create a 'cozy' feeling in a bedroom using colour?",
        ["Use only cool colours on all surfaces", "Layer warm tones in varying depths and textures", "Paint all walls in bright white", "Use a single flat colour everywhere"], 1,
        "Layering warm tones at different depths (lighter on walls, deeper on textiles) creates visual warmth and dimension. Combining these with varied textures amplifies the cozy effect."),
      q("When using warm colours in a bedroom, what technique prevents the space from feeling overwhelming?",
        ["Use the same intensity on every surface", "Balance warm tones with neutral anchors", "Add more saturated colours", "Remove all textiles"], 1,
        "Neutral anchors (cream, taupe, soft grey) give the eye a place to rest and prevent warm colours from becoming visually exhausting. This balance is key to sophisticated warm interiors."),
      q("Which undertone should you look for in white paint when pairing it with warm bedroom colours?",
        ["Blue undertone", "Green undertone", "Yellow or pink undertone", "Purple undertone"], 2,
        "Whites with warm undertones (yellow, pink, or peach) harmonise with warm colour schemes. A cool-undertone white would clash and create visual tension in a warm palette."),
      q("What percentage of the bedroom should typically be in your dominant warm colour?",
        ["10%", "30%", "60%", "90%"], 2,
        "Following the 60-30-10 rule, your dominant colour should cover approximately 60% of the space (walls, large furniture). This creates cohesion while leaving room for secondary and accent colours."),
    ],
  },
  {
    course_slug: "the-alchemic-kitchen",
    course_title_hint: "The alchemic KITCHEN",
    quiz_title: "Module 3 · Kitchen — Knowledge Check",
    description: "Functional beauty: cool colours, serene spaces, sophisticated cool designs.",
    passing_score: 70,
    max_attempts: 3,
    questions: [
      q("Why are cool colours particularly effective in kitchen design?",
        ["They make food look more appetising", "They create a clean, fresh, and calming atmosphere", "They make the space feel smaller", "They hide stains better"], 1,
        "Cool colours (blues, greens, soft greys) evoke cleanliness and calm — essential qualities in a kitchen where hygiene and focus are important. They also visually expand smaller kitchen spaces."),
      q("Which cool colour is most versatile for kitchen cabinetry?",
        ["Bright turquoise", "Navy blue", "Sage green", "Lavender"], 2,
        "Sage green works with virtually any countertop material, pairs beautifully with both warm wood tones and cool metals, and transitions well between traditional and contemporary styles."),
      q("How can you add warmth to a predominantly cool-toned kitchen without disrupting the palette?",
        ["Paint all walls bright orange", "Introduce natural wood elements and warm metallics", "Replace all cool colours with warm ones", "Add neon lighting"], 1,
        "Natural wood (cutting boards, open shelving, flooring) and warm metallics (brass, copper hardware) add warmth through material rather than wall colour, maintaining the cool palette's serenity."),
      q("What is 'colour drenching' and how does it work in a kitchen?",
        ["Using many different colours in one space", "Painting walls, cabinets, and trim in the same colour family", "Adding water-themed artwork", "Using only primary colours"], 1,
        "Colour drenching means enveloping a space in one colour across multiple surfaces (walls, cabinetry, trim, ceiling). In kitchens, this creates a sophisticated, seamless look that makes the space feel larger."),
      q("Which cool colour combination creates the most sophisticated kitchen design?",
        ["Baby blue and bright pink", "Deep teal paired with soft grey and white marble", "Lime green and electric blue", "All surfaces in pure white"], 1,
        "Deep teal provides drama and depth, soft grey offers a sophisticated neutral bridge, and white marble adds luxury and light. This layered approach creates visual interest without chaos."),
    ],
  },
  {
    course_slug: "the-elemental-bathroom",
    course_title_hint: "The elemental BATHROOM",
    quiz_title: "Module 4 · Bathrooms — Knowledge Check",
    description: "Luxurious experience: neutral palette, layering neutrals, neutral with accents.",
    passing_score: 70,
    max_attempts: 3,
    questions: [
      q("What makes neutral colours ideal for bathroom design?",
        ["They are the cheapest paint colours", "They create a spa-like, timeless atmosphere", "They don't require good lighting", "They hide mould better"], 1,
        "Neutrals (whites, creams, taupes, greys) evoke the tranquillity of luxury spas. They're timeless, meaning your bathroom won't feel dated as trends change, and they let natural materials shine."),
      q("How do you prevent an all-neutral bathroom from looking flat and boring?",
        ["Add bright neon accents", "Layer different neutral tones with varied textures", "Use only one shade of beige", "Add busy wallpaper patterns"], 1,
        "Layering neutrals means combining different values (light cream walls, medium taupe vanity, dark charcoal floor) with varied textures (matte tile, glossy fixtures, woven baskets). This creates depth and interest."),
      q("Which accent colour pairs best with a warm neutral bathroom palette?",
        ["Neon green", "Muted brass or gold", "Bright red", "Electric purple"], 1,
        "Muted brass and gold hardware add warmth and luxury to neutral bathrooms without competing with the serene palette. They function as a 'warm metallic accent' that elevates the entire space."),
      q("What is the most important consideration when choosing white for a bathroom?",
        ["Always choose the brightest white available", "Consider the undertone relative to your lighting and fixtures", "White is white — there's no difference", "Only use white on ceilings"], 1,
        "There are hundreds of 'white' paints, each with different undertones (pink, yellow, blue, green). The wrong undertone can clash with tiles, vanity, and fixtures. Always test whites in your specific lighting conditions."),
      q("How should you introduce a pop of colour into a neutral bathroom?",
        ["Paint all walls in a bold colour", "Use easily changeable elements like towels, plants, and artwork", "Install coloured plumbing fixtures", "Use coloured grout between tiles"], 1,
        "Changeable accents (towels, candles, plants, artwork) let you refresh the colour story seasonally without renovation. This keeps the expensive, permanent elements neutral and timeless."),
    ],
  },
  {
    course_slug: "the-soulful-living-room",
    course_title_hint: "The soulful LIVING ROOM",
    quiz_title: "Module 5 · Living — Knowledge Check",
    description: "Bringing people together: complementary theory, dynamic interiors, balancing contrast.",
    passing_score: 70,
    max_attempts: 3,
    questions: [
      q("What are complementary colours?",
        ["Colours that are next to each other on the colour wheel", "Colours that are directly opposite each other on the colour wheel", "Colours that are all the same hue", "Colours that are all neutral"], 1,
        "Complementary colours sit at 180° from each other on the colour wheel (e.g., blue/orange, red/green, yellow/purple). They create maximum visual energy and are perfect for lively living spaces."),
      q("How should you use complementary colours in a living room to avoid visual chaos?",
        ["Use both colours in equal amounts at full saturation", "Use one as dominant (muted) and the other as accent (smaller doses)", "Only use them on the ceiling", "Mix them together into one colour"], 1,
        "The key to complementary harmony is imbalance: one colour dominates (often in a muted version) while its complement appears in smaller, strategic doses as accents. Equal amounts create visual competition."),
      q("What is a 'split complementary' colour scheme?",
        ["Using one colour and the two colours adjacent to its complement", "Splitting one wall into two colours", "Using only half of the colour wheel", "Mixing complementary colours together"], 0,
        "Split complementary uses one base colour plus the two colours flanking its complement (e.g., blue + yellow-orange + red-orange). It offers contrast with less tension than direct complements."),
      q("Which element is most effective for introducing a complementary accent in a living room?",
        ["Ceiling paint", "Statement cushions, artwork, or a single accent chair", "All the curtains", "The entire sofa"], 1,
        "Small, intentional doses of the complementary accent (cushions, art, a single chair) create dynamic focal points without overwhelming the space. The accent should draw the eye, not dominate it."),
      q("Why is contrast important in living room design?",
        ["It makes the room look smaller", "It creates visual interest and defines different zones", "It's only for modern styles", "It makes furniture look cheaper"], 1,
        "Contrast (in colour, value, or texture) prevents a living room from feeling monotonous. It guides the eye through the space, highlights architectural features, and helps define functional zones within open-plan areas."),
    ],
  },
  {
    course_slug: "the-crafted-dining-room",
    course_title_hint: "The crafted DINING ROOM",
    quiz_title: "Module 6 · Dining — Knowledge Check",
    description: "Inviting environments: analogous theory, harmonious designs, sophisticated analogous palettes.",
    passing_score: 70,
    max_attempts: 3,
    questions: [
      q("What are analogous colours?",
        ["Colours opposite each other on the wheel", "Colours that sit next to each other on the colour wheel", "Only neutral colours", "Primary colours only"], 1,
        "Analogous colours are neighbours on the colour wheel (e.g., yellow, yellow-green, green). They create naturally harmonious, cohesive palettes because they share underlying pigments."),
      q("Why are analogous colour schemes particularly suited to dining rooms?",
        ["They make food look bigger", "They create a harmonious, intimate atmosphere ideal for conversation", "They are the cheapest to implement", "They make the room look larger"], 1,
        "Analogous palettes feel cohesive and calming without being monotonous. This harmony encourages lingering at the table, fostering conversation and connection — the primary purpose of a dining room."),
      q("How many colours should you typically include in an analogous scheme?",
        ["Exactly 2", "3 to 5 adjacent colours", "All 12 colours on the wheel", "Only 1"], 1,
        "An effective analogous scheme uses 3-5 neighbouring colours. Fewer than 3 can feel too simple; more than 5 starts to lose the cohesive quality that makes analogous schemes work."),
      q("What technique adds sophistication to an analogous dining room palette?",
        ["Using all colours at the same saturation", "Varying the value (light to dark) within the analogous range", "Adding a completely unrelated colour", "Using only the brightest versions"], 1,
        "Varying value (lightness/darkness) within your analogous range creates depth and hierarchy. For example, a blue-green scheme might use pale mint walls, medium teal upholstery, and deep navy accents."),
      q("Which analogous palette would create the most inviting dining atmosphere?",
        ["Ice blue, steel grey, and white", "Warm amber, burnt sienna, and deep burgundy", "Neon green, lime, and chartreuse", "Black, charcoal, and dark grey"], 1,
        "Warm analogous palettes (amber → sienna → burgundy) create intimacy and appetite appeal. These earth-adjacent tones feel welcoming and complement food presentation beautifully."),
    ],
  },
  {
    course_slug: "catalyst-workspace",
    course_title_hint: "Catalyst WORKSPACE",
    quiz_title: "Module 7 · Home Office — Knowledge Check",
    description: "Productivity and focus: monochromatic fundamentals, texture and contrast, monochromatic in practice.",
    passing_score: 70,
    max_attempts: 3,
    questions: [
      q("What is a monochromatic colour scheme?",
        ["Using only black and white", "Using various tints, shades, and tones of a single hue", "Using every colour of the rainbow", "Using only primary colours"], 1,
        "Monochromatic means 'one colour' — but it's not boring. By using the full range of tints (adding white), shades (adding black), and tones (adding grey) of one hue, you create a sophisticated, cohesive space."),
      q("Why is a monochromatic scheme effective for a home office?",
        ["It's the cheapest option", "It minimises visual distraction and promotes focus", "It makes the room look bigger", "It's the current trend"], 1,
        "A monochromatic palette reduces visual noise — there are no competing colour relationships to process. This calm, unified environment helps maintain concentration during work."),
      q("How do you add visual interest to a monochromatic home office?",
        ["Add a completely different colour", "Vary textures, materials, and finishes within the same colour", "Use only flat matte surfaces", "Add busy patterns"], 1,
        "Texture is the secret weapon of monochromatic design. Combining matte walls, glossy desk surfaces, woven textiles, and brushed metal in the same colour family creates richness without colour distraction."),
      q("Which single colour is most recommended for a productive home office monochromatic scheme?",
        ["Bright red", "Blue-grey or soft blue", "Vivid yellow", "Hot pink"], 1,
        "Blue tones are scientifically associated with focus, calm, and productivity. A blue-grey monochromatic scheme (from pale sky to deep navy) creates an environment that supports sustained concentration."),
      q("What role does contrast play in a monochromatic scheme?",
        ["It should be avoided entirely", "It creates depth and prevents the space from feeling flat", "It only works with multiple colours", "It makes the room feel chaotic"], 1,
        "Value contrast (the difference between light and dark versions of your chosen hue) is essential in monochromatic design. Without it, the space feels one-dimensional. Aim for at least 3 distinct values."),
    ],
  },
  {
    course_slug: "kids-legacy-draft",
    course_title_hint: "Kids",
    quiz_title: "Module 8 · Kids — Knowledge Check",
    description: "Growing spaces: the 60-30-10 rule, creating focal points, strategic accents.",
    passing_score: 70,
    max_attempts: 3,
    questions: [
      q("What is the 60-30-10 rule in interior design?",
        ["60% furniture, 30% decor, 10% lighting", "60% dominant colour, 30% secondary colour, 10% accent colour", "60% floor, 30% walls, 10% ceiling", "60% budget on paint, 30% on furniture, 10% on accessories"], 1,
        "The 60-30-10 rule is a timeless proportion guide: 60% of the room in a dominant colour (usually walls/large surfaces), 30% in a secondary colour (furniture/textiles), and 10% in an accent (accessories/art)."),
      q("How should the 60-30-10 rule be adapted for children's rooms?",
        ["Use 60% in the brightest colour possible", "Keep the 60% calm/neutral and use the 10% accent for playful, changeable elements", "Ignore the rule entirely for kids", "Use 60% black"], 1,
        "A calm dominant colour (60%) ensures the room doesn't overstimulate. The 10% accent in playful colours (cushions, art, toys) can be easily updated as the child grows and their tastes change."),
      q("What is a 'focal point' in room design?",
        ["The most expensive item in the room", "The area that first draws the eye when entering the space", "The centre of the room", "The window"], 1,
        "A focal point is the visual anchor — where your eye naturally lands first. In kids' rooms, this might be an accent wall, a reading nook, or a creative display area. It gives the room purpose and direction."),
      q("How can you create a focal point in a children's room using colour?",
        ["Paint every wall a different colour", "Use a bold or contrasting colour on one feature wall or zone", "Use the darkest colour on the ceiling", "Avoid colour entirely"], 1,
        "A single feature wall or zone in a bolder colour creates a natural focal point. This could be behind the bed, around a reading corner, or framing a play area — giving the room visual structure."),
      q("What is the advantage of using 'strategic accents' in a child's room?",
        ["They are permanent and never need changing", "They allow the room to evolve as the child grows without repainting", "They are always the most expensive option", "They only work in large rooms"], 1,
        "Strategic accents (cushions, bedding, wall art, rugs) in the 10% accent colour can be swapped affordably as your child's interests change — from dinosaurs to space to music — without touching walls or furniture."),
    ],
  },
  {
    course_slug: "knowledgeable-cheat-sheets",
    course_title_hint: "Knowledgeable CHEAT SHEETS",
    quiz_title: "Module 9 · All Things Design — Knowledge Check",
    description: "Advanced concepts: natural light effects, artificial lighting, choosing colours for your light.",
    passing_score: 70,
    max_attempts: 3,
    questions: [
      q("How does natural light affect the appearance of paint colours?",
        ["Natural light has no effect on colour", "Colours shift throughout the day as light direction and intensity change", "Natural light only affects white colours", "Colours look the same in all lighting"], 1,
        "Natural light changes colour temperature throughout the day — warm golden morning light, neutral midday, cool blue afternoon. A paint colour can look completely different at 8am vs 4pm. Always test colours at multiple times."),
      q("Which direction of natural light produces the warmest colour rendering?",
        ["North-facing (in the Southern Hemisphere)", "West-facing during afternoon/evening", "East-facing at midnight", "Light direction doesn't matter"], 1,
        "West-facing rooms receive warm, golden afternoon and evening light that enhances warm colours and adds warmth to cool colours. This is important when selecting paint — cool colours may appear warmer than expected."),
      q("What is the Kelvin scale used for in interior lighting?",
        ["Measuring room temperature", "Measuring the colour temperature of light (warm to cool)", "Measuring paint thickness", "Measuring room size"], 1,
        "The Kelvin scale measures light colour temperature: 2700K is warm/yellow (like candlelight), 4000K is neutral white, and 6500K is cool/blue (like daylight). This directly affects how paint colours appear."),
      q("What Kelvin temperature is recommended for living areas to complement warm colour schemes?",
        ["6500K (cool daylight)", "2700K–3000K (warm white)", "1000K (candlelight)", "5000K (bright white)"], 1,
        "2700K–3000K produces a warm, inviting glow that enhances warm colours and softens cool colours. This temperature range is ideal for living rooms, bedrooms, and dining areas where ambience matters."),
      q("What is the best practice for choosing paint colours relative to your room's lighting?",
        ["Choose colours under store fluorescent lighting", "Test large paint samples in your actual room at different times of day", "Only look at colours on a computer screen", "Choose the colour that looks best at midnight"], 1,
        "Always test A4-sized (or larger) paint samples on your actual walls and observe them at morning, midday, and evening under both natural and artificial light. Colours behave differently in every unique space."),
    ],
  },
  {
    course_slug: "enchanted-outdoors",
    course_title_hint: "Enchanted OUTDOORS",
    quiz_title: "Module 10 · Outdoors — Knowledge Check",
    description: "Beautiful outdoor areas: current colour trends, personal style, timeless design principles.",
    passing_score: 70,
    max_attempts: 3,
    questions: [
      q("What is the most important factor when choosing colours for outdoor spaces?",
        ["Following the latest Instagram trends", "Considering how colours interact with natural surroundings and intense sunlight", "Using only grey and white", "Matching the neighbour's house"], 1,
        "Outdoor colours must work with nature (greenery, sky, soil) and withstand intense UV light that can wash out or alter colours. What looks perfect indoors may appear completely different under direct sunlight."),
      q("How do current colour trends for 2026 influence outdoor design?",
        ["You must follow every trend exactly", "Trends inspire accent choices while timeless neutrals anchor the space", "Trends don't apply to outdoor spaces", "Only use trending colours on permanent structures"], 1,
        "Use trends for easily changeable elements (cushions, planters, outdoor textiles) while keeping permanent structures (decking, walls, fencing) in timeless colours. This lets you refresh without renovation."),
      q("What defines 'personal style' in outdoor colour design?",
        ["Copying a designer's portfolio exactly", "A consistent colour story that reflects your taste and lifestyle", "Using as many colours as possible", "Only using colours from one era"], 1,
        "Personal style emerges when you identify the colours, materials, and moods that consistently attract you. It's the thread that connects your choices and makes a space feel authentically yours rather than generic."),
      q("Which principle ensures outdoor colour choices remain timeless?",
        ["Using only trendy colours", "Grounding the palette in nature-inspired tones that complement the landscape", "Avoiding all colour", "Changing colours every season"], 1,
        "Nature-inspired palettes (earth tones, greens, sky blues, stone greys) never go out of style because they inherently harmonise with the outdoor environment. They create a seamless indoor-outdoor connection."),
      q("What is the 'timeless design' approach to outdoor colour?",
        ["Never change anything", "Invest in quality neutrals for permanent elements and express personality through accessories", "Only use black and white", "Follow whatever is trending on social media"], 1,
        "Timeless design separates the permanent (structure, hardscaping, large furniture) from the seasonal (textiles, plants, decor). Permanent elements in classic colours ensure longevity; accessories allow creative expression."),
    ],
  },
];
