CREATE TABLE public.deal_terms_acceptances (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  email text,
  deal_slug text NOT NULL,
  terms_version text NOT NULL DEFAULT '1.0',
  accepted_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX deal_terms_acceptances_user_idx ON public.deal_terms_acceptances (user_id);
CREATE INDEX deal_terms_acceptances_slug_idx ON public.deal_terms_acceptances (deal_slug);

GRANT SELECT, INSERT ON public.deal_terms_acceptances TO authenticated;
GRANT ALL ON public.deal_terms_acceptances TO service_role;

ALTER TABLE public.deal_terms_acceptances ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can record their own terms acceptance"
ON public.deal_terms_acceptances FOR INSERT TO authenticated
WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users can view their own terms acceptance"
ON public.deal_terms_acceptances FOR SELECT TO authenticated
USING (user_id = auth.uid());

CREATE POLICY "Admins can view all terms acceptances"
ON public.deal_terms_acceptances FOR SELECT TO authenticated
USING (public.has_role(auth.uid(), 'admin'));