// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omzwtfnqffseemrlylwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tend0Zm5xZmZzZWVtcmx5bHd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE1NTA0MjksImV4cCI6MjA5NzEyNjQyOX0.WvzIywSWUP3ZDweA_WZlH0lMU1e8OObvJ3vMZKQgTME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});